package com.define.domain;

public class Person {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.id
     *
     * @mbg.generated Thu Aug 27 13:54:32 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.name
     *
     * @mbg.generated Thu Aug 27 13:54:32 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.cetifi_core
     *
     * @mbg.generated Thu Aug 27 13:54:32 CST 2020
     */
    private String cetifiCore;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.id
     *
     * @return the value of person.id
     *
     * @mbg.generated Thu Aug 27 13:54:32 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.id
     *
     * @param id the value for person.id
     *
     * @mbg.generated Thu Aug 27 13:54:32 CST 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.name
     *
     * @return the value of person.name
     *
     * @mbg.generated Thu Aug 27 13:54:32 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.name
     *
     * @param name the value for person.name
     *
     * @mbg.generated Thu Aug 27 13:54:32 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.cetifi_core
     *
     * @return the value of person.cetifi_core
     *
     * @mbg.generated Thu Aug 27 13:54:32 CST 2020
     */
    public String getCetifiCore() {
        return cetifiCore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.cetifi_core
     *
     * @param cetifiCore the value for person.cetifi_core
     *
     * @mbg.generated Thu Aug 27 13:54:32 CST 2020
     */
    public void setCetifiCore(String cetifiCore) {
        this.cetifiCore = cetifiCore;
    }
}